apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-amazing-jenkins
  namespace: my-amazing-namespace
  labels: 
    'radapp.io/application': test-app
    'radapp.io/environment': dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-my-amazing-jenkins
  template:
    metadata:
      labels:
        app: redis-my-amazing-jenkins
        'radapp.io/application': test-app
        'radapp.io/environment': dev
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.5"
      - name: redis-monitor
        image: redis
        args:
        - 'redis-cli'
        - '-h'
        - 'localhost'
        - 'MONITOR'
        resources:
          limits:
            cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: my-amazing-jenkins
  namespace: my-amazing-namespace
spec:
  selector:
    app: redis-my-amazing-jenkins
    'radapp.io/application': test-app
    'radapp.io/environment': ENVIRONMENT_PLACEHOLD
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP