apiVersion: v1
kind: Secret
metadata:
  name: NAME_PLACEHOLDER
  namespace: NAMESPACE_PLACEHOLDER
  labels: 
    'radapp.io/application': APPLICATION_PLACEHOLDER
    'radapp.io/environment': ENVIRONMENT_PLACEHOLDER
data: {}