apiVersion: apps/v1
kind: Deployment
metadata:
  name: NAME_PLACEHOLDER
  namespace: NAMESPACE_PLACEHOLDER
  labels: 
    'radapp.io/application': APPLICATION_PLACEHOLDER
    'radapp.io/environment': ENVIRONMENT_PLACEHOLDER
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-NAME_PLACEHOLDER
  template:
    metadata:
      labels:
        app: redis-NAME_PLACEHOLDER
        'radapp.io/application': APPLICATION_PLACEHOLDER
        'radapp.io/environment': ENVIRONMENT_PLACEHOLDER
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.5"
      - name: redis-monitor
        image: redis
        args:
        - 'redis-cli'
        - '-h'
        - 'localhost'
        - 'MONITOR'
        resources:
          limits:
            cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: NAME_PLACEHOLDER
  namespace: NAMESPACE_PLACEHOLDER
spec:
  selector:
    app: redis-NAME_PLACEHOLDER
    'radapp.io/application': APPLICATION_PLACEHOLDER
    'radapp.io/environment': ENVIRONMENT_PLACEHOLD
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP